[server]
headless = true
address = "127.0.0.1"
port = 8501
baseUrlPath = "nano"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0a960a"
secondaryBackgroundColor = "#e6e6ff"
textColor = "#000000"